---
title: "Proj1"
author: "Aidan B"
date: "2025-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

import libraries

```{r}
library(here)
library(ggplot2)
library(dplyr)
library(maps)
```

Get all datasets

```{r}
catOwnership <- read.csv(here("Data", "CatOwnershipRate2016.csv"))
                          
dogOwnership <- read.csv(here("Data", "DogOwnershipRate2016.csv"))
                          
petOwnership <- read.csv(here("Data", "PetOwnershipRate.csv"))

state_map <- map_data("state")



head(catOwnership)
head(dogOwnership)
head(petOwnership)
head(state_map)


```

Rename some other columns to make the data easy to distinguish and work with

```{r}

colnames(state_map) <- c("long", "lat", "group", "order", "region", "subregion")

head(state_map)


colnames(catOwnership) <- c("cat_ranking", "region", "cat_rate")
head(catOwnership)


colnames(dogOwnership) <- c("dog_ranking", "region", "dog_rate")
head(dogOwnership)


colnames(petOwnership) <- c("pet_ranking", "region", "pet_rate")
head(petOwnership)


```

Decapitalize state names in pet maps

```{r}
catOwnership$region <- tolower(catOwnership$region)
head(catOwnership)

dogOwnership$region <- tolower(dogOwnership$region)
head(dogOwnership)

petOwnership$region <- tolower(petOwnership$region)
head(petOwnership)
```

Join datasets together

```{r}
state_map <- left_join(state_map, catOwnership, by = "region")

state_map <- left_join(state_map, dogOwnership, by = "region")

state_map <- left_join(state_map, petOwnership, by = "region")

head(state_map)

```

USe ggplot to show different rates across the USA

First for pets in general

```{r}
discr_graph1 <- ggplot(state_map, aes(x = long, y = lat, group = group)) + geom_polygon(aes(fill = pet_rate), color = "black") + scale_fill_viridis_c() + labs(x = "longitude", y = "latitude", title = "Percentage of families with pets per state", fill = "% Rate")


discr_graph1
```

then for cats

```{r}
discr_graph1 <- ggplot(state_map, aes(x = long, y = lat, group = group)) + geom_polygon(aes(fill = cat_rate), color = "pink") + scale_fill_viridis_c() + labs(x = "longitude", y = "latitude", title = "Percentage of families with cats per state", fill = "% Rate")



discr_graph1
```



First for dogs in general

```{r}
discr_graph1 <- ggplot(state_map, aes(x = long, y = lat, group = group)) + geom_polygon(aes(fill = dog_rate), color = "blue") + scale_fill_viridis_c() + labs(x = "longitude", y = "latitude", title = "Percentage of families with dogs per state", fill = "% Rate")



discr_graph1

show(state_map)
```

Order the map to put the most dog friendly state at the top
```{r}
sorted <- arrange(state_map,dog_ranking)

sorted
  
  
```


